name: deploy

on:
  deployment


env:
  TARGET_ENV: ${{ github.event.deployment.environment }}

jobs:

  Test-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Print-ENV
        run: |
          echo "${{ env.TARGET_ENV }}"

  deploy:
    name: Deploy
    # permissions:
    #   deployments: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3.3.0

      - name: Update deployment status (in_progress)
        uses: chrnorm/deployment-status@v2.0.1
        with:
          token: '${{ github.token }}'
          state: 'in_progress'
          # deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          deployment-id: ${{ github.event.deployment.id }} # ${{ github.event.deployment_id }}
      
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2.0.1
        with:
          token: '${{ github.token }}'
          state: 'success'
          # deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          deployment-id: ${{ github.event.deployment.id }} # ${{ github.event.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          # environment-url: ${{ github.event. }}
          state: 'failure'
          # deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          deployment-id: ${{ github.event.deployment.id }}
